# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: Data Docs
email: kevinhcaldwell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Kevin's Blog for all Projects!
baseurl: "/data-decode" # the subpath of your site, e.g. /blog
url: "https://kevin-caldwell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: kevinhcal
github_username:  Kevin-Caldwell

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-latex

markdown: kramdown
